// <auto-generated />
using System;
using DoItApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoItApi.Migrations
{
    [DbContext(typeof(DoItDbContext))]
    [Migration("20190713162325_AddedIsCompletedFlagForTasks")]
    partial class AddedIsCompletedFlagForTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DIA.Core.Models.AlertTime", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("DiaTaskId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("Time");

                    b.Property<DateTimeOffset>("UpdatedDate");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DiaTaskId");

                    b.ToTable("AlertTime");
                });

            modelBuilder.Entity("DIA.Core.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("DiaTaskId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<DateTimeOffset>("UpdatedDate");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DiaTaskId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DIA.Core.Models.DiaTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<DateTimeOffset>("DueDateTime");

                    b.Property<bool>("IsCompleted");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("TaskDescription")
                        .IsRequired();

                    b.Property<DateTimeOffset>("UpdatedDate");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DIA.Core.Models.AlertTime", b =>
                {
                    b.HasOne("DIA.Core.Models.DiaTask")
                        .WithMany("AlertTimes")
                        .HasForeignKey("DiaTaskId");
                });

            modelBuilder.Entity("DIA.Core.Models.Comment", b =>
                {
                    b.HasOne("DIA.Core.Models.DiaTask")
                        .WithMany("Comments")
                        .HasForeignKey("DiaTaskId");
                });
#pragma warning restore 612, 618
        }
    }
}
